# Generated by Django 4.0.5 on 2022-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('post', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=32)),
                ('cooler', models.CharField(max_length=32)),
                ('mobo', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('psu', models.CharField(max_length=32)),
                ('gpu', models.CharField(max_length=32)),
                ('storage', models.CharField(max_length=32)),
                ('case', models.CharField(max_length=32)),
            ],
        ),
    ]
